-- ============================================
-- AlphaOS 完整数据库架构脚本 (v2.0)
-- ============================================
-- 此脚本整合了所有历史迁移文件，是单一真理来源。
-- 包含：基础交易表、日志、用户偏好、自动化规则、信号、AI训练集
-- ============================================

-- 1. 基础交易表 (trades) 与 账户表 (accounts)
-- ============================================
CREATE TABLE IF NOT EXISTS accounts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name VARCHAR(100) DEFAULT '默认账户',
  initial_balance DECIMAL(15, 2) NOT NULL DEFAULT 10000.00,
  current_balance DECIMAL(15, 2) NOT NULL DEFAULT 10000.00,
  currency VARCHAR(10) DEFAULT 'USD',
  broker VARCHAR(100),
  account_number VARCHAR(100),
  account_type VARCHAR(50) DEFAULT 'demo' CHECK (account_type IN ('demo', 'live')),
  notes TEXT
);

CREATE TABLE IF NOT EXISTS trades (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  account_id UUID REFERENCES accounts(id) ON DELETE CASCADE,
  
  symbol VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL CHECK (side IN ('buy', 'sell')),
  entry_price DECIMAL(15, 5) NOT NULL,
  exit_price DECIMAL(15, 5),
  quantity DECIMAL(15, 4) NOT NULL,
  entry_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  exit_time TIMESTAMP WITH TIME ZONE,
  
  pnl_net DECIMAL(15, 2) DEFAULT 0,
  pnl_gross DECIMAL(15, 2) DEFAULT 0,
  commission DECIMAL(15, 4) DEFAULT 0,
  swap DECIMAL(15, 4) DEFAULT 0,
  
  stop_loss DECIMAL(15, 5),
  take_profit DECIMAL(15, 5),
  risk_reward_ratio DECIMAL(10, 2),
  
  status VARCHAR(10) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'cancelled')),
  order_type VARCHAR(20) DEFAULT 'market',
  
  notes TEXT,
  tags TEXT[],
  strategies TEXT[],
  
  external_order_id VARCHAR(100) UNIQUE,
  external_ticket VARCHAR(100),
  source VARCHAR(50) DEFAULT 'manual',
  
  screenshot_urls TEXT[],
  mae DECIMAL(15, 5) DEFAULT 0,
  mfe DECIMAL(15, 5) DEFAULT 0
);

-- 2. 交易日志 (journal_notes)
-- ============================================
CREATE TABLE IF NOT EXISTS journal_notes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  date DATE NOT NULL UNIQUE,
  content TEXT NOT NULL,
  mood VARCHAR(20),
  tags TEXT[],
  daily_pnl DECIMAL(15, 2)
);

-- 3. 用户偏好 (user_preferences)
-- ============================================
CREATE TABLE IF NOT EXISTS user_preferences (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id VARCHAR(100) DEFAULT 'default_user' UNIQUE,
  display_name VARCHAR(100) DEFAULT '交易员',
  timezone VARCHAR(50) DEFAULT 'Asia/Shanghai',
  risk_level VARCHAR(20) DEFAULT 'medium',
  theme VARCHAR(20) DEFAULT 'dark'
);

-- 4. 信号系统 (signals) - 核心表
-- ============================================
CREATE TABLE IF NOT EXISTS signals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  symbol VARCHAR(20) NOT NULL,
  action VARCHAR(10) NOT NULL CHECK (action IN ('BUY', 'SELL')),
  price DECIMAL(15, 5),
  sl DECIMAL(15, 5),
  tp DECIMAL(15, 5),
  
  status VARCHAR(20) DEFAULT 'new' CHECK (status IN ('new', 'viewed', 'processed', 'ignored', 'expired')),
  source VARCHAR(50) DEFAULT 'mt5_indicator',
  raw_data JSONB,
  comment TEXT
);

-- 5. 自动化规则 (automation_rules) - 支持 AI 配置
-- ============================================
CREATE TABLE IF NOT EXISTS automation_rules (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    symbol TEXT NOT NULL,
    is_enabled BOOLEAN DEFAULT false NOT NULL,
    fixed_lot_size NUMERIC DEFAULT 0.01 NOT NULL,
    max_spread_points INTEGER DEFAULT 50 NOT NULL,
    strategy_id TEXT,
    
    -- Phase 5 AI 字段
    ai_mode VARCHAR(20) DEFAULT 'legacy', -- legacy, indicator_ai, pure_ai
    ai_confidence_threshold DECIMAL(3,2) DEFAULT 0.75,
    pure_ai_features JSONB DEFAULT '{}',

    user_id UUID REFERENCES auth.users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_automation_rules_symbol ON automation_rules(symbol);

-- 6. AI 训练数据集 (training_datasets) - Phase 5 新增
-- ============================================
CREATE TABLE IF NOT EXISTS public.training_datasets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  signal_id UUID REFERENCES public.signals(id),
  symbol TEXT NOT NULL,
  
  features JSONB NOT NULL,      -- 特征快照
  market_context JSONB,         -- 市场上下文 (K线)
  label INTEGER,                -- 0=亏损, 1=盈利
  model_version TEXT DEFAULT 'v0',
  notes TEXT
);

-- ============================================
-- RLS 策略设置 (Row Level Security)
-- ============================================
-- 启用 RLS
ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE training_datasets ENABLE ROW LEVEL SECURITY;

-- 创建宽松策略 (允许匿名访问 - 适用于个人/本地部署)
-- 注意：如果需要多用户隔离，请修改为基于 auth.uid() 的策略
CREATE POLICY "Enable all for all users" ON accounts FOR ALL USING (true);
CREATE POLICY "Enable all for all users" ON trades FOR ALL USING (true);
CREATE POLICY "Enable all for all users" ON journal_notes FOR ALL USING (true);
CREATE POLICY "Enable all for all users" ON user_preferences FOR ALL USING (true);
CREATE POLICY "Enable all for all users" ON signals FOR ALL USING (true);
CREATE POLICY "Enable all for all users" ON automation_rules FOR ALL USING (true);
CREATE POLICY "Enable all for all users" ON training_datasets FOR ALL USING (true);

-- ============================================
-- 触发器与函数
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 应用 updated_at 触发器
CREATE TRIGGER update_accounts_updated_at BEFORE UPDATE ON accounts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_trades_updated_at BEFORE UPDATE ON trades FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_journal_notes_updated_at BEFORE UPDATE ON journal_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_preferences_updated_at BEFORE UPDATE ON user_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_signals_updated_at BEFORE UPDATE ON signals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_automation_rules_updated_at BEFORE UPDATE ON automation_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 插入默认数据
-- ============================================
INSERT INTO user_preferences (user_id, display_name, timezone)
VALUES ('default_user', 'Alpha Trader', 'Asia/Shanghai')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO automation_rules (symbol, is_enabled, fixed_lot_size, max_spread_points, ai_mode, ai_confidence_threshold)
VALUES ('GLOBAL', false, 0.01, 50, 'legacy', 0.75)
ON CONFLICT (symbol) DO NOTHING;

