FROM python:3.11-slim

WORKDIR /app

# Since context is '..' (trading-bridge/), files are relative to that.
# requirements.txt is in docker/ folder.
COPY docker/requirements.txt .
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements.txt

COPY src/ /app/src/

WORKDIR /app/src
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
