# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import alphaos_pb2 as alphaos__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in alphaos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlphaZeroStub(object):
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSignals = channel.stream_stream(
                '/alphaos.AlphaZero/StreamSignals',
                request_serializer=alphaos__pb2.SignalResponse.SerializeToString,
                response_deserializer=alphaos__pb2.SignalRequest.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/alphaos.AlphaZero/HealthCheck',
                request_serializer=alphaos__pb2.Ping.SerializeToString,
                response_deserializer=alphaos__pb2.Pong.FromString,
                _registered_method=True)


class AlphaZeroServicer(object):
    """The service definition
    """

    def StreamSignals(self, request_iterator, context):
        """Bidirectional stream: Server sends SignalRequest, Client sends SignalResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Unary call for simple ping/health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlphaZeroServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSignals': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSignals,
                    request_deserializer=alphaos__pb2.SignalResponse.FromString,
                    response_serializer=alphaos__pb2.SignalRequest.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=alphaos__pb2.Ping.FromString,
                    response_serializer=alphaos__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'alphaos.AlphaZero', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('alphaos.AlphaZero', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlphaZero(object):
    """The service definition
    """

    @staticmethod
    def StreamSignals(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/alphaos.AlphaZero/StreamSignals',
            alphaos__pb2.SignalResponse.SerializeToString,
            alphaos__pb2.SignalRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/alphaos.AlphaZero/HealthCheck',
            alphaos__pb2.Ping.SerializeToString,
            alphaos__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
