from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import asyncio
import uuid
import time
import os
from supabase import create_client, Client

app = FastAPI(title="MT5 Trading Bridge (HTTP)")

# 简单的内存队列和存储
command_queue = []
last_status = {}
active_symbols = {} # { "EURUSD": { "bid": 1.1, "ask": 1.2, "last_seen": 1234567890 } }
last_trade = None  # Stores the most recent trade execution

# 历史数据请求存储 { request_id: asyncio.Future }
history_requests: Dict[str, asyncio.Future] = {}

class TradeRequest(BaseModel):
    action: str # BUY, SELL, CLOSE
    symbol: Optional[str] = None
    volume: Optional[float] = 0.01
    sl: Optional[float] = 0.0
    tp: Optional[float] = 0.0
    ticket: Optional[int] = 0
    type: Optional[str] = "TRADE" # TRADE or PENDING
    price: Optional[float] = 0.0 # For Pending Orders

class StatusUpdate(BaseModel):
    account: dict  # { balance, equity, margin, free_margin }
    positions: List[dict] # [{ ticket, symbol, type, volume, pnl, sl, tp ... }]
    # Legacy support
    symbol: Optional[str] = None
    bid: Optional[float] = None
    ask: Optional[float] = None

class TradeReport(BaseModel):
    ticket: int
    symbol: str
    type: str  # "BUY" or "SELL"
    volume: float
    price: float
    time: str  # ISO timestamp or similar

class HistoryData(BaseModel):
    request_id: str
    symbol: str
    timeframe: str
    data: List[Dict[str, Any]] # List of candles
    count: int

# ...

@app.post("/trade/execute")
async def execute_trade(trade: TradeRequest):
    command = {
        "type": trade.type if trade.type else "TRADE",
        "action": trade.action,
        "symbol": trade.symbol,
        "volume": trade.volume,
        "sl": trade.sl,
        "tp": trade.tp,
        "ticket": trade.ticket,
        "price": trade.price
    }
    command_queue.append(command)
    return {"status": "queued", "queue_length": len(command_queue)}

@app.post("/trade/report")
async def report_trade(report: TradeReport):
    global last_trade
    last_trade = report.dict()
    print(f"Trade Reported: {last_trade}")
    
    # Auto-Journaling to Supabase
    supabase_url = os.environ.get("SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_KEY")
    
    if supabase_url and supabase_key:
        try:
            supabase: Client = create_client(supabase_url, supabase_key)
            
            # Map MT5 data to Supabase schema
            db_side = report.type.lower() # "BUY" -> "buy"
            
            data = {
                "symbol": report.symbol,
                "side": db_side,
                "quantity": report.volume,
                "entry_price": report.price,
                "status": "open",
                "notes": f"MT5 Ticket: {report.ticket}",
                # "created_at" will be auto-generated by DB or we can send it
                "pnl_net": 0,
                "pnl_gross": 0,
                "commission": 0,
                "swap": 0
            }
            
            supabase.table("trades").insert(data).execute()
            print("Trade synced to Supabase")
        except Exception as e:
            print(f"Failed to sync to Supabase: {e}")
    
    return {"status": "received"}

@app.get("/commands/pop")
async def pop_command():
    if command_queue:
        return command_queue.pop(0)
    return None

@app.post("/status/update")
async def update_status(status: StatusUpdate):
    global last_status
    
    # Debug: Print positions count if any
    if status.positions:
        print(f"Received {len(status.positions)} positions from EA")
        # Sample log to verify data structure
        if len(status.positions) > 0:
            print(f"First position sample: {status.positions[0]}")
    else:
        print("Received status update with NO positions")
    
    last_status = status.dict()
    
    # Update active symbols list
    if status.symbol:
        active_symbols[status.symbol] = {
            "bid": status.bid,
            "ask": status.ask,
            "last_seen": time.time()
        }
    
    # Prune old symbols (older than 10s)
    current_time = time.time()
    to_remove = [s for s, data in active_symbols.items() if current_time - data["last_seen"] > 10]
    for s in to_remove:
        del active_symbols[s]
        
    return {"status": "received"}

@app.get("/status")
async def get_status():
    return {
        "bridge_status": "connected",
        "last_mt5_update": last_status,
        "active_symbols": list(active_symbols.keys()),
        "symbol_prices": active_symbols,
        "pending_commands": len(command_queue),
        "last_trade": last_trade  # Expose last trade to frontend
    }

@app.get("/health")
async def health_check():
    return {"status": "ok"}

# --- History Data Endpoints ---

@app.get("/history")
async def get_history(symbol: str, timeframe: str, count: int = 1000):
    request_id = str(uuid.uuid4())
    
    command = {
        "type": "GET_HISTORY",
        "request_id": request_id,
        "symbol": symbol,
        "timeframe": timeframe,
        "count": count
    }
    
    # Create a future to wait for the response
    loop = asyncio.get_running_loop()
    future = loop.create_future()
    history_requests[request_id] = future
    
    # Queue the command for EA
    command_queue.append(command)
    
    try:
        # Wait for data with timeout (e.g., 30 seconds)
        data = await asyncio.wait_for(future, timeout=30.0)
        return data
    except asyncio.TimeoutError:
        # Clean up if timed out
        if request_id in history_requests:
            del history_requests[request_id]
        raise HTTPException(status_code=504, detail="Timeout waiting for MT5 response")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/data/history")
async def receive_history(history: HistoryData):
    req_id = history.request_id
    
    if req_id in history_requests:
        future = history_requests[req_id]
        if not future.done():
            future.set_result(history.dict())
        del history_requests[req_id]
        return {"status": "accepted"}
    
    return {"status": "ignored", "reason": "request_id not found or expired"}
